name: Release Chimera packages

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node and PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set up .npmrc for Cloudsmith
        run: |
          echo "@chimera:registry=https://npm.cloudsmith.io/${{ secrets.CLOUDSMITH_USER }}/${{ secrets.CLOUDSMITH_REPO }}/" > ~/.npmrc
          echo "//npm.cloudsmith.io/${{ secrets.CLOUDSMITH_USER }}/${{ secrets.CLOUDSMITH_REPO }}/:_authToken=${{ secrets.CLOUDSMITH_TOKEN }}" >> ~/.npmrc

      - name: Install dependencies
        run: pnpm install

      - name: Run Chromatic
        run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }}

      - name: Apply version bumps and changelogs
        run: pnpm changeset version

      - name: Commit version bumps (if needed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(release): version bump" || echo "Nothing to commit"

      - name: Push changes
        run: git push origin main

      - name: Publish updated packages
        run: pnpm -r --filter @chimera/* publish --access public --no-git-checks
