name: Publish packages to Cloudsmith

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node and PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Set up .npmrc for Cloudsmith
        run: |
          echo "@chimera:registry=https://npm.cloudsmith.io/${{ secrets.CLOUDSMITH_USER }}/${{ secrets.CLOUDSMITH_REPO }}/" > ~/.npmrc
          echo "//npm.cloudsmith.io/${{ secrets.CLOUDSMITH_USER }}/${{ secrets.CLOUDSMITH_REPO }}/:_authToken=${{ secrets.CLOUDSMITH_TOKEN }}" >> ~/.npmrc

      - name: Build packages
        run: pnpm build

      - name: Publish packages
        run: pnpm -r publish --access public --no-git-checks
